<?php

return [
    'deprecated' => [

    ],
    'labels' => [

    ],
    'descriptions' => [
        'accordion' => 'A vertically stacked set of interactive headings that each reveal a section of content.',
        'alert' => 'Displays a callout for user attention.',
        'alert-dialog' => 'A modal dialog that interrupts the user with important content and expects a response.',
        'aspect-ratio' => 'Displays content within a desired ratio.',
        'attachment' => 'Displays a file or image attachment with media, metadata, upload state, and actions.',
        'avatar' => 'An image element with a fallback for representing the user.',
        'badge' => 'Displays a badge or a component that looks like a badge.',
        'breadcrumb' => 'Displays the path to the current resource using a hierarchy of links.',
        'bubble' => 'Displays conversational content in a message bubble. Supports variants, alignment, grouping, reactions, and collapsible content.',
        'button' => 'Displays a button or a component that looks like a button.',
        'button-group' => 'A container that groups related buttons together with consistent styling.',
        'card' => 'Displays a card with header, content, and footer.',
        'checkbox' => 'A control that allows the user to toggle between checked and not checked.',
        'collapsible' => 'An interactive component which expands/collapses a panel.',
        'dialog' => 'A window overlaid on either the primary window or another dialog window, rendering the content underneath inert.',
        'empty' => 'Use the Empty component to display an empty state.',
        'field' => 'Combine labels, controls, and help text to compose accessible form fields and grouped inputs.',
        'hover-card' => 'For sighted users to preview content available behind a link.',
        'input' => 'A text input component for forms and user data entry with built-in styling and accessibility features.',
        'input-group' => 'Displays an input with inline or stacked addons and actions.',
        'item' => 'A versatile component for displaying content with media, title, description, and actions.',
        'kbd' => 'Used to display textual user input from keyboard.',
        'marker' => 'Displays an inline status, system note, bordered row, or labeled separator in a conversation.',
        'native-select' => 'A styled native HTML select element with consistent design system integration.',
        'pagination' => 'Pagination with page navigation, next and previous links.',
        'popover' => 'Displays rich content in a portal, triggered by a button.',
        'progress' => 'Displays an indicator showing the completion progress of a task, typically displayed as a progress bar.',
        'radio-group' => 'A set of checkable buttons—known as radio buttons—where no more than one of the buttons can be checked at a time.',
        'separator' => 'Visually or semantically separates content.',
        'sheet' => 'Extends the Dialog component to display content that complements the main content of the screen.',
        'skeleton' => 'Use to show a placeholder while content is loading.',
        'spinner' => 'An indicator that can be used to show a loading state.',
        'switch' => 'A control that allows the user to toggle between checked and not checked.',
        'table' => 'A responsive table component.',
        'tabs' => 'A set of layered sections of content—known as tab panels—that are displayed one at a time.',
        'textarea' => 'Displays a form textarea or a component that looks like a textarea.',
        'toggle' => 'A two-state button that can be either on or off.',
        'toggle-group' => 'A set of two-state buttons that can be toggled on or off.',
        'tooltip' => 'A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.',
    ],
];
